version: '3'
services:
  database:
    image: postgres:14
    container_name: db_dev
    ports:
      - 5432:5432
    env_file:
      - ./database/.env
    volumes:
      - dbdata:/var/lib/postgresql/database

volumes:
  dbdata:
    name: vol_dev